/* Company display name -> official website domain(s), for logos in the money rivers.
   Built 30 Sep 2026. A composite name maps to one domain per company, in display order.
   An empty array means no reliable domain (generic group or unresolved); the UI shows initials. */
window.COMPANY_DOMAINS = {
  "FANUC": ["fanuc.co.jp"],
  "ABB Robotics": ["abb.com"],
  "Yaskawa": ["yaskawa.co.jp"],
  "KUKA (Midea)": ["kuka.com"],
  "Estun / Inovance": ["estun.com", "inovance.com"],
  "NEURA Robotics": ["neura-robotics.com"],
  "Standard Bots": ["standardbots.com"],
  "Mech-Mind": ["mech-mind.com"],
  "Abagy": ["abagy.com"],
  "Universal Robots (Teradyne)": ["universal-robots.com"],
  "FANUC CRX / Doosan / Techman": ["fanuc.co.jp", "doosanrobotics.com", "tm-robot.com"],
  "AUBO / JAKA": ["aubo-cobot.com", "jaka.com"],
  "Dyna Robotics": ["dyna.co"],
  "Franka Robotics": ["franka.de"],
  "Genesis AI": ["genesis.ai"],
  "Rockwell / Siemens": ["rockwellautomation.com", "siemens.com"],
  "JR Automation (Hitachi)": ["jrautomation.com"],
  "Bastian (Toyota Industries)": ["bastiansolutions.com"],
  "Dematic (KION SCS)": ["dematic.com"],
  "Formic": ["formic.co"],
  "Vention": ["vention.io"],
  "Intrinsic (Alphabet)": ["intrinsic.ai"],
  "RemBrain": ["rembrain.ai"],
  "Geek+": ["geekplus.com"],
  "Locus Robotics": ["locusrobotics.com"],
  "MiR (Teradyne)": ["mobile-industrial-robots.com"],
  "Hikrobot": ["hikrobotics.com"],
  "Agility Robotics": ["agilityrobotics.com"],
  "Dexterity": ["dexterity.ai"],
  "Amazon Robotics": ["amazon.com"],
  "Symbotic": ["symbotic.com"],
  "AutoStore": ["autostoresystem.com"],
  "Ocado": ["ocadogroup.com"],
  "Exotec / Hai Robotics": ["exotec.com", "hairobotics.com"],
  "Covariant (in Amazon)": ["covariant.ai"],
  "Ambi Robotics": ["ambirobotics.com"],
  "Verity": ["verity.net"],
  "Intuitive Surgical": ["intuitive.com"],
  "Medtronic Hugo": ["medtronic.com"],
  "J&J Ottava": ["jnj.com"],
  "Stryker Mako / Zimmer ROSA": ["stryker.com", "zimmerbiomet.com"],
  "Moon Surgical": ["moonsurgical.com"],
  "LEM Surgical": ["lemsurgical.com"],
  "Proprio / Activ Surgical": ["propriovision.com", "activsurgical.com"],
  "DJI": ["dji.com"],
  "Parrot / Teledyne FLIR": ["parrot.com", "flir.com"],
  "Zipline": ["flyzipline.com"],
  "Skydio": ["skydio.com"],
  "Quantum Systems": ["quantum-systems.com"],
  "Ukrainian producers": [],
  "Roborock": ["roborock.com"],
  "Ecovacs": ["ecovacs.com"],
  "Dreame": ["dreametech.com"],
  "iRobot": ["irobot.com"],
  "1X NEO": ["1x.tech"],
  "Sunday (Memo)": ["sunday.ai"],
  "Matic Robots": ["maticrobots.com"],
  "Tesla Optimus": ["tesla.com"],
  "Boston Dynamics (Hyundai)": ["bostondynamics.com"],
  "UBTech": ["ubtrobot.com"],
  "XPeng IRON": ["xpeng.com"],
  "Figure": ["figure.ai"],
  "Unitree": ["unitree.com"],
  "AgiBot": ["agibot.com"],
  "Apptronik": ["apptronik.com"],
  "Agility": ["agilityrobotics.com"],
  "1X": ["1x.tech"],
  "Galbot": ["galbot.com"],
  "NEURA": ["neura-robotics.com"],
  "Lely": ["lely.com"],
  "DeLaval / GEA": ["delaval.com", "gea.com"],
  "John Deere": ["deere.com"],
  "DJI Agras": ["dji.com"],
  "Carbon Robotics": ["carbonrobotics.com"],
  "Monarch Tractor / Burro / Aigen": ["monarchtractor.com", "burro.ai", "aigen.io"],
  "Lockheed / General Dynamics / BAE": ["lockheedmartin.com", "gd.com", "baesystems.com"],
  "Rheinmetall / Kratos / L3Harris": ["rheinmetall.com", "kratosdefense.com", "l3harris.com"],
  "AeroVironment": ["avinc.com"],
  "Anduril": ["anduril.com"],
  "Shield AI": ["shield.ai"],
  "Helsing": ["helsing.ai"],
  "Saronic": ["saronic.com"],
  "Keenon / Pudu": ["keenon.com", "pudurobotics.com"],
  "Brain Corp": ["braincorp.com"],
  "Komatsu / Caterpillar / EACON": ["komatsu.com", "caterpillar.com", "eacon.com"],
  "All3": ["all3.com"],
  "Autonomics": ["autonomics.tech"],
  "Built Robotics": ["builtrobotics.com"],
  "NVIDIA": ["nvidia.com"],
  "Google DeepMind": ["deepmind.google"],
  "Tesla": ["tesla.com"],
  "Physical Intelligence": ["physicalintelligence.company"],
  "Skild AI": ["skild.ai"],
  "Generalist": ["generalistai.com"],
  "Positronic Robotics": ["positronic.ro"],
  "Rhoda (ex-Asimov)": ["rhoda.ai"],
  "CARYATID": ["caryatid.ai"],
  "Archetype AI": ["archetypeai.io"],
  "Yaskawa / Inovance / Panasonic": ["yaskawa.co.jp", "inovance.com", "panasonic.com"],
  "Nidec / Maxon / Kollmorgen": ["nidec.com", "maxongroup.com", "kollmorgen.com"],
  "Sanhua / Tuopu": ["zjshc.com", "tuopu.com"],
  "Tesla, Figure, Apptronik, 1X": ["tesla.com", "figure.ai", "apptronik.com", "1x.tech"],
  "Nabtesco": ["nabtesco.com"],
  "Harmonic Drive Systems": ["hds.co.jp"],
  "Sumitomo": ["shi.co.jp"],
  "Leaderdrive (Green Harmonic)": ["leaderdrive.com"],
  "Keyence": ["keyence.com"],
  "Cognex": ["cognex.com"],
  "SICK / Basler": ["sick.com", "baslerweb.com"],
  "Hesai / RoboSense / Ouster": ["hesaitech.com", "robosense.ai", "ouster.com"],
  "Orbbec / Zivid": ["orbbec.com", "zivid.com"],
  "GelSight / Meta Digit": ["gelsight.com", "meta.com"],
  "Qualcomm": ["qualcomm.com"],
  "Horizon Robotics": ["horizon.auto"],
  "TI / STMicro / Infineon": ["ti.com", "st.com", "infineon.com"],
  "Hailo / SiMa.ai / Tenstorrent": ["hailo.ai", "sima.ai", "tenstorrent.com"],
  "AeroSilicon": ["aerosilicon.it"],
  "CATL": ["catl.com"],
  "BYD / LGES / Samsung SDI": ["byd.com", "lgensol.com", "samsungsdi.com"],
  "EVE / Panasonic": ["evebattery.com", "panasonic.com"],
  "Amprius": ["amprius.com"],
  "Foxconn": ["foxconn.com"],
  "Jabil / Flex": ["jabil.com", "flex.com"],
  "Guangdong humanoid plant": [],
  "Machina Labs": ["machinalabs.ai"],
  "Divergent": ["divergent3d.com"],
  "Schunk / Zimmer / Robotiq / OnRobot": ["schunk.com", "zimmer-group.com", "robotiq.com", "onrobot.com"],
  "Intuitive instruments": ["intuitive.com"],
  "Sharpa": ["sharpa.com"],
  "Shadow / Inspire / Tesollo": ["shadowrobot.com", "inspire-robots.com", "tesollo.com"],
  "Genesis AI + Wuji": ["genesis.ai", "wuji.tech"],
  "FANUC / Siemens / Rockwell / Beckhoff": ["fanuc.co.jp", "siemens.com", "rockwellautomation.com", "beckhoff.com"],
  "NVIDIA Isaac / GR00T": ["nvidia.com"],
  "Physical Intelligence / Skild / Generalist / Dyna": ["physicalintelligence.company", "skild.ai", "generalistai.com", "dyna.co"],
  "Intrinsic / Viam / Foxglove": ["intrinsic.ai", "viam.com", "foxglove.dev"],
  "Rhoda": ["rhoda.ai"],
  "Rockwell / Siemens / JR Automation / Dematic": ["rockwellautomation.com", "siemens.com", "jrautomation.com", "dematic.com"],
  "SIASUN": ["siasun.com"],
  "Chinese data-collection centres": [],
  "Formic / Vention / Standard Bots": ["formic.co", "vention.io", "standardbots.com"],
  "Apptronik Robot Park": ["apptronik.com"],
  "FANUC Service": ["fanuc.co.jp"],
  "Intuitive": ["intuitive.com"],
  "Locus / Agility": ["locusrobotics.com", "agilityrobotics.com"],
  "Formant / InOrbit": ["formant.io", "inorbit.ai"],
  "NVIDIA / Google DeepMind": ["nvidia.com", "deepmind.google"],
  "Tesla / Hyundai-BD": ["tesla.com", "bostondynamics.com"],
  "Figure / Skild / Apptronik": ["figure.ai", "skild.ai", "apptronik.com"],
  "Positronic": ["positronic.ro"],
  "KUKA": ["kuka.com"],
  "Teradyne Robotics": ["teradyne.com"],
  "Suncor": ["suncor.com"],
  "Aramco": ["aramco.com"],
  "Aramco Ventures": ["aramco.com"],
  "Chevron Technology Ventures": ["chevron.com"],
  "Equinor Ventures / bp ventures / Shell Ventures": ["equinor.com", "bp.com", "shell.com"],
  "Evok Innovations": ["evokinnovations.com"],
  "Halliburton Labs": ["halliburtonlabs.com"],
  "Covestro / Gerdau": ["covestro.com", "gerdau.com"],
  "BASF Venture Capital": ["basf.com"],
  "Evonik Venture Capital": ["evonik.com"],
  "Emerald Technology Ventures": ["emerald-ventures.com"],
  "BHP": ["bhp.com"],
  "Rio Tinto": ["riotinto.com"],
  "Anglo American / Glencore": ["angloamerican.com", "glencore.com"],
  "ArcelorMittal / thyssenkrupp": ["arcelormittal.com", "thyssenkrupp.com"],
  "BHP Ventures": ["bhp.com"],
  "Vale Ventures": ["vale.com"],
  "ArcelorMittal XCarb Innovation Fund": ["arcelormittal.com"],
  "Caterpillar Ventures": ["caterpillar.com"],
  "Teck": ["teck.com"],
  "National Grid / Kansai Electric": ["nationalgrid.com", "kepco.co.jp"],
  "Energy Impact Partners": ["energyimpactpartners.com"],
  "National Grid Partners": ["ngpartners.com"],
  "Energize Capital": ["energizecap.com"],
  "Siemens Energy Ventures / Engie New Ventures / Verbund X": ["siemens-energy.com", "engie.com", "verbund.com"],
  "Mercedes-Benz / Caterpillar / Bridgestone": ["mercedes-benz.com", "caterpillar.com", "bridgestone.com"],
  "Hitachi Ventures": ["hitachi-ventures.com"],
  "Next47 (Siemens)": ["next47.com"],
  "SE Ventures (Schneider)": ["seventures.com"],
  "ABB Ventures": ["abb.com"],
  "Bosch Ventures": ["bosch-ventures.com"],
  "Nestle / Nespresso": ["nestle.com", "nespresso.com"],
  "Tyson Ventures": ["tysonfoods.com"],
  "Nestle via Emerald": ["nestle.com", "emerald-ventures.com"],
  "Saint-Gobain NOVA / General Mills 301 INC": ["saint-gobain.com", "generalmills.com"],
  "Kajima": ["kajima.co.jp"],
  "PermitFlow": ["permitflow.com"],
  "Liberty Mutual Strategic Ventures": ["libertymutual.com"],
  "CRH Ventures / Holcim MAQER": ["crh.com", "holcim.com"],
  "Procore": ["procore.com"],
  "Deutsche Bahn Digital Ventures": ["deutschebahn.com"],
  "Munich Re Ventures / AXA Venture Partners": ["munichre.com", "axavp.com"],
  "Siemens Digital Industries": ["siemens.com"],
  "Emerson": ["emerson.com"],
  "ABB": ["abb.com"],
  "Rockwell": ["rockwellautomation.com"],
  "Honeywell": ["honeywell.com"],
  "Schneider": ["se.com"],
  "Yokogawa": ["yokogawa.com"],
  "Mitsubishi Electric": ["mitsubishielectric.com"],
  "Imubit": ["imubit.com"],
  "Fero Labs": ["ferolabs.com"],
  "Siemens Eigen Engineering Agent": ["siemens.com"],
  "Endress+Hauser": ["endress.com"],
  "ABB Measurement & Analytics": ["abb.com"],
  "Siemens Process Instrumentation / VEGA / Krohne": ["siemens.com", "vega.com", "krohne.com"],
  "Augury": ["augury.com"],
  "Percepto": ["percepto.co"],
  "Siemens DI Software": ["siemens.com"],
  "AVEVA (Schneider)": ["aveva.com"],
  "AspenTech (Emerson)": ["aspentech.com"],
  "Dassault Systemes": ["3ds.com"],
  "PTC": ["ptc.com"],
  "Bentley": ["bentley.com"],
  "Octave (ex-Hexagon ALI)": ["octave.com"],
  "Honeywell Forge / SAP / IBM Maximo": ["honeywell.com", "sap.com", "ibm.com"],
  "Cognite": ["cognite.com"],
  "Tulip": ["tulip.co"],
  "Seeq": ["seeq.com"],
  "Samsara": ["samsara.com"],
  "INImakini (Makini)": ["makini.io"],
  "Sybilion": ["sybilion.com"],
  "Palantir": ["palantir.com"],
  "C3.ai": ["c3.ai"],
  "Microsoft / NVIDIA / Google Cloud": ["microsoft.com", "nvidia.com", "cloud.google.com"],
  "Aramco METABRAIN": ["aramco.com"],
  "The Forecasting Company": ["theforecastingcompany.com"],
  "AiSupervision": ["aisupervision.com"],
  "KUKA / Yaskawa": ["kuka.com", "yaskawa.co.jp"],
  "Komatsu / Caterpillar": ["komatsu.com", "caterpillar.com"],
  "Boston Dynamics": ["bostondynamics.com"],
  "Gecko Robotics": ["geckorobotics.com"],
  "ANYbotics": ["anybotics.com"],
  "Korial (ex-Energy Robotics)": ["korial.com"],
  "3M": ["3m.com"],
  "MSA Safety": ["msasafety.com"],
  "Draeger": ["draeger.com"],
  "Ansell": ["ansell.com"],
  "PIP / Odyssey": ["pipglobal.com", "odysseyinvestment.com"],
  "Sick / Pilz / Rockwell": ["sick.com", "pilz.com", "rockwellautomation.com"],
  "Voxel": ["voxelai.com"],
  "Protex AI": ["protex.ai"],
  "Intenseye": ["intenseye.com"],
  "Kinetic": ["wearkinetic.com"],
  "Blackline Safety": ["blacklinesafety.com"],
  "Wolters Kluwer Enablon": ["wolterskluwer.com"],
  "Sphera (Blackstone)": ["sphera.com"],
  "Cority (Thoma Bravo)": ["cority.com"],
  "Intelex (Fortive)": ["intelex.com"],
  "Ideagen (Hg)": ["ideagen.com"],
  "VelocityEHS (CVC) / Benchmark Gensuite": ["ehs.com", "benchmarkgensuite.com"],
  "Mitti by SafetyCulture": ["mitti.com"],
  "Aatmunn (ex-Guardhat)": ["aatmunn.com"],
  "StrongArm": ["strongarmtech.com"],
  "Augmentir": ["augmentir.com"],
  "Humand": ["humand.co"],
  "Fortinet / Palo Alto / Tenable OT": ["fortinet.com", "paloaltonetworks.com", "tenable.com"],
  "ServiceNow": ["servicenow.com"],
  "Accenture": ["accenture.com"],
  "Dragos": ["dragos.com"],
  "Claroty": ["claroty.com"],
  "Armis": ["armis.com"],
  "Nozomi": ["nozominetworks.com"],
  "TXOne": ["txone.com"],
  "Rockwell Lifecycle Services": ["rockwellautomation.com"],
  "Yokogawa projects": ["yokogawa.com"],
  "Worley": ["worley.com"],
  "Wood (Sidara) / Jacobs / Fluor": ["woodplc.com", "jacobs.com", "fluor.com"],
  "dss+": ["consultdss.com"],
  "ERM (KKR)": ["erm.com"],
  "Accenture Industry X / Capgemini": ["accenture.com", "capgemini.com"],
  "LandingAI": ["landing.ai"],
  "PhysicsX": ["physicsx.ai"],
  "Emerson / Siemens / Honeywell service": ["emerson.com", "siemens.com", "honeywell.com"],
  "Draeger Services": ["draeger.com"],
  "Bureau Veritas / Mistras / SGS": ["bureauveritas.com", "mistrasgroup.com", "sgs.com"],
  "Siemens Senseye": ["siemens.com"],
  "Uptake": ["uptake.com"],
  "Siemens / ABB / Schneider / Emerson / Rockwell": ["siemens.com", "abb.com", "se.com", "emerson.com"],
  "3M / MSA / Draeger / Ansell": ["3m.com", "msasafety.com", "draeger.com", "ansell.com"],
  "ANYbotics / Gecko": ["anybotics.com", "geckorobotics.com"],
  "Blackline": ["blacklinesafety.com"],
  "Worley / Wood / Jacobs": ["worley.com", "woodplc.com", "jacobs.com"],
  "CSIA integrators": [],
  "Siemens Eigen": ["siemens.com"],
  "Rockwell Design Studio Copilot": ["rockwellautomation.com"],
  "ABB / Emerson / Siemens / Yokogawa service": ["abb.com", "emerson.com", "siemens.com", "yokogawa.com"],
  "Bureau Veritas / Mistras / TUV": ["bureauveritas.com", "mistrasgroup.com"],
  "Gecko / ANYbotics / Korial": ["geckorobotics.com", "anybotics.com", "korial.com"],
  "MSA / 3M / Ansell": ["msasafety.com", "3m.com", "ansell.com"],
  "Grainger / Fastenal / Wesco": ["grainger.com", "fastenal.com", "wesco.com"],
  "PTC / Bentley / Dassault / Hexagon": ["ptc.com", "bentley.com", "3ds.com", "hexagon.com"],
  "AVEVA / AspenTech": ["aveva.com", "aspentech.com"],
  "Siemens": ["siemens.com"],
  "MSA": ["msasafety.com"],
  "Wesco": ["wesco.com"],
  "Graybar": ["graybar.com"],
  "Grainger / Fastenal / Rexel": ["grainger.com", "fastenal.com", "rexel.com"],
  "Kinetic via Nationwide": ["wearkinetic.com", "nationwide.com"],
  "Voxel via Gallagher": ["voxelai.com", "ajg.com"],
  "SE Ventures portfolio": ["seventures.com"],
  "Emerson Software & Control": ["emerson.com"],
  "Hexagon": ["hexagon.com"],
  "ABB Automation / Schneider IA / Yokogawa": ["abb.com", "se.com", "yokogawa.com"],
  "Draeger Safety": ["draeger.com"],
  "ERM": ["erm.com"],
  "DEKRA / TUV / DNV / Bureau Veritas": ["dekra.com", "dnv.com", "bureauveritas.com"],
  "exida": ["exida.com"],
  "Interplay Learning": ["interplaylearning.com"],
  "Poka (IFS)": ["poka.io"],
};
