/* Card heading text -> company domain, for logos on report cards (logos.js).
   Exact-match only: a heading gets a logo when its trimmed text equals a key.
   Products map to the company that owns them. Ambiguous names are left out. */
window.LOGO_NAMES = {
  'AIVA': 'aiva.ai',
  'AMD': 'amd.com',
  'AMD — accelerator commitments': 'amd.com',
  'AWS': 'aws.amazon.com',
  'Agentforce Help Agent': 'salesforce.com',
  'Agibot': 'agibot.com',
  'Agility Robotics': 'agilityrobotics.com',
  'Alphabet': 'abc.xyz',
  'Amazon': 'amazon.com',
  'Anthropic': 'anthropic.com',
  'Apple': 'apple.com',
  'Apptronik': 'apptronik.com',
  'Arista': 'arista.com',
  'Avride': 'avride.ai',
  'Baidu Apollo Go': 'apollo.auto',
  'Blue Cross Blue Shield': 'bcbs.com',
  'Bolt': 'bolt.new',
  'Bolt.new': 'bolt.new',
  'Broadcom': 'broadcom.com',
  'Broadcom & custom silicon': 'broadcom.com',
  'Cartesia Sonic 3': 'cartesia.ai',
  'ChatGPT Work': 'openai.com',
  'Circle Nanopayments': 'circle.com',
  'Claude': 'claude.ai',
  'Claude Code': 'claude.ai',
  'Claude Fable 5': 'claude.ai',
  'Codex 2.0': 'openai.com',
  'Coinbase AgentKit': 'coinbase.com',
  'Collectly — DVC portfolio': 'collectly.co',
  'CoreWeave': 'coreweave.com',
  'Cursor': 'cursor.com',
  'Decagon': 'decagon.ai',
  'Decart': 'decart.ai',
  'DeepSeek': 'deepseek.com',
  'DeepSeek — V4 Preview': 'deepseek.com',
  'Devin': 'devin.ai',
  'Doctronic — DVC portfolio': 'doctronic.ai',
  'ElevenLabs': 'elevenlabs.io',
  'ElevenLabs v3': 'elevenlabs.io',
  'Etched — the ASIC bet got funded': 'etched.com',
  'Fable 5 / Mythos 5': 'anthropic.com',
  'Figure AI': 'figure.ai',
  'Firefly 5': 'adobe.com',
  'Fish Audio S1': 'fish.audio',
  'FleetWorks': 'fleetworks.ai',
  'Flux 2': 'bfl.ai',
  'GPT Image 1.5': 'openai.com',
  'GPT-5.6 Luna': 'openai.com',
  'GPT-5.6 Sol': 'openai.com',
  'GPT-5.6 Sol / Terra / Luna': 'openai.com',
  'Gatik': 'gatik.ai',
  'Gemini 3.5 Flash Cyber': 'gemini.google.com',
  'Gemini 3.6 Flash': 'gemini.google.com',
  'Gen-4.5': 'runwayml.com',
  'Genie 3': 'deepmind.google',
  'GitHub Copilot': 'github.com',
  'Google': 'google.com',
  'Google Cloud': 'cloud.google.com',
  'Google DeepMind': 'deepmind.google',
  'Grammarly': 'grammarly.com',
  'Grok 4.5': 'x.ai',
  'Grok Imagine': 'x.ai',
  'Hailuo 2.3': 'hailuoai.video',
  'Harvey': 'harvey.ai',
  'Higgsfield': 'higgsfield.ai',
  'Hunyuan3D 3.0': 'hunyuan.tencent.com',
  'HunyuanVideo': 'hunyuan.tencent.com',
  'Ideogram 3.0': 'ideogram.ai',
  'Imagen 4': 'deepmind.google',
  'Included Health': 'includedhealth.com',
  'Inworld': 'inworld.ai',
  'Jules': 'jules.google',
  'Kling 3.0': 'klingai.com',
  'Kodiak': 'kodiak.ai',
  'LMNT': 'lmnt.com',
  'Lovable': 'lovable.dev',
  'Luma Genie': 'lumalabs.ai',
  'Luma Ray2': 'lumalabs.ai',
  'Lyria 3 Pro': 'deepmind.google',
  'Manus': 'manus.im',
  'Marble': 'worldlabs.ai',
  'Marvell': 'marvell.com',
  'Meshy': 'meshy.ai',
  'Meta': 'meta.com',
  'Microsoft': 'microsoft.com',
  'Microsoft IC': 'microsoft.com',
  'Midjourney v8': 'midjourney.com',
  'MiniMax': 'minimax.io',
  'Mistral': 'mistral.ai',
  'Moonshot': 'kimi.com',
  'Moonshot — Kimi K3': 'kimi.com',
  'Muse Spark 1.1': 'meta.com',
  'NEAR Protocol': 'near.org',
  'NVIDIA': 'nvidia.com',
  'NVIDIA — label the period': 'nvidia.com',
  'Nano Banana': 'gemini.google.com',
  'Nebius': 'nebius.com',
  'NemoClaw': 'nvidia.com',
  'Neura Robotics': 'neura-robotics.com',
  'OpenAI': 'openai.com',
  'OpenAI TTS': 'openai.com',
  'OpenAI — real-time voice': 'openai.com',
  'Oracle': 'oracle.com',
  'Perplexity': 'perplexity.ai',
  'Perplexity Personal Computer': 'perplexity.ai',
  'Physical Intelligence': 'physicalintelligence.company',
  'Pika 2.5': 'pika.art',
  'Pony.ai': 'pony.ai',
  'Recraft V4': 'recraft.ai',
  'Replit': 'replit.com',
  'Replit Agent': 'replit.com',
  'Rodin': 'hyper3d.ai',
  'Runway': 'runwayml.com',
  'Salesforce AI': 'salesforce.com',
  'Seedream 5.0': 'bytedance.com',
  'Sequoia': 'sequoiacap.com',
  'Sesame CSM': 'sesame.com',
  'Sierra': 'sierra.ai',
  'Skild AI': 'skild.ai',
  'Sora': 'openai.com',
  'Sora 2': 'openai.com',
  'SpaceXAI': 'x.ai',
  'Stable Audio 2.5': 'stability.ai',
  'StepFun': 'stepfun.com',
  'Stripe x402': 'stripe.com',
  'Suno': 'suno.com',
  'Suno v5': 'suno.com',
  'Tesla': 'tesla.com',
  'Tesla Optimus': 'tesla.com',
  'Tesla Robotaxi': 'tesla.com',
  'TRELLIS.2': 'microsoft.com',
  'Tripo': 'tripo3d.ai',
  'Udio': 'udio.com',
  'Unitree': 'unitree.com',
  'Veo 3.1': 'deepmind.google',
  'Waabi': 'waabi.ai',
  'Wabi': 'wabi.ai',
  'Waymo': 'waymo.com',
  'Wayve': 'wayve.ai',
  'WeRide': 'weride.ai',
  'Windsurf': 'windsurf.com',
  'Zhipu AI': 'z.ai',
  'Zoox': 'zoox.com',
  'xAI': 'x.ai'
};
