/* DVC portfolio company -> official website domain, for logos in the portfolio section (sec13.js).
   Built 30 Sep 2026. Empty string = unresolved; the UI keeps the initials. */
window.PORTFOLIO_DOMAINS = {
  "Perplexity": "perplexity.ai",
  "Animation": "animation.inc",
  "Skim.ai": "",
  "HyperC": "hyperc.com",
  "Firmly": "firmly.ai",
  "Bina School": "thebinaschool.com",
  "Pervasive App": "pervasive.app",
  "Howie AI": "howie.ai",
  "Aurora First": "aurorafirst.ai",
  "Jome": "jome.com",
  "Pinscreen": "pinscreen.com",
  "Promethean AI": "prometheanai.com",
  "BerryApp": "berryapp.io",
  "Beacons": "beacons.ai",
  "GPU Audio": "gpu.audio",
  "Dwelly": "dwelly.group",
  "PermitFlow": "permitflow.com",
  "Humand": "humand.co",
  "Kick": "kick.co",
  "Parafin": "parafin.com",
  "Eloquent AI": "eloquentai.co",
  "Unreal Labs": "unreallabs.ai",
  "Wrkdn": "wrkdn.com",
  "Docdraft": "docdraft.ai",
  "The Forecasting Company": "theforecastingcompany.com",
  "Keye": "keye.co",
  "Avoca": "avoca.ai",
  "Realytics": "realytics.com",
  "tely.ai": "tely.ai",
  "Aglide": "aglide.com",
  "FleetWorks": "fleetworks.ai",
  "Docsum": "docsum.ai",
  "Generative Alpha": "galpha.ai",
  "Solve Intelligence": "solveintelligence.com",
  "Aviary AI": "helloaviary.ai",
  "JustPaid.io": "justpaid.ai",
  "Vasco": "vasco.app",
  "Agentnoon": "",
  "Intento": "inten.to",
  "RemoFirst": "remofirst.com",
  "Fura": "fura.com",
  "Motives": "motives.ai",
  "Sybilion": "sybilion.com",
  "Zinit": "zinit.com",
  "Qualified Health": "qualifiedhealthai.com",
  "Bioptic": "bioptic.io",
  "Lovi": "lovi.care",
  "Doctronic": "doctronic.ai",
  "FitWise": "thefitwise.com",
  "Kerna Laboratorie": "kernalabs.ai",
  "Hona AI": "hona.com",
  "Red Sky Health": "redskyhealth.com",
  "Curex": "getcurex.com",
  "Collectly": "collectly.co",
  "NutriSense": "nutrisense.io",
  "Denti.ai": "denti.ai",
  "Asylia Dx": "asyliadx.com",
  "Higgsfield": "higgsfield.ai",
  "Etched": "etched.com",
  "Wabi": "wabi.ai",
  "DoubleFifth": "coannotate.com",
  "superglu": "superglue.cloud",
  "CopilotKit": "copilotkit.ai",
  "Zencoder": "zencoder.ai",
  "The Stage AI": "thestage.ai",
  "HackerPulse": "hackerpulse.com",
  "Makini": "makini.io",
  "Eternis Labs": "eternis.ai",
  "Paradigm": "paradigmai.com",
  "Sutro": "withsutro.com",
  "mem0": "mem0.ai",
  "Datachain": "datachain.ai",
  "LightBeam.ai": "lightbeam.ai",
  "Hercules": "zerosystems.com",
  "Honeydew": "honeydew.ai",
  "GetGenAI": "getgen.ai",
  "Defog.ai": "defog.ai",
  "Strong Compute": "strongcompute.com",
  "evidently.ai": "evidentlyai.com",
  "Alter Labs": "alterauth.com",
  "Archetype": "archetypeai.io",
  "DeepFlow AI": "deepflow.com",
  "Rhoda AI": "rhoda.ai",
  "Matic Robots": "maticrobots.com",
  "Abagy Robotics": "abagy.com",
  "Thinking Machines Lab": "thinkingmachines.ai",
  "Sooth Labs": "soothlabs.com",
  "SentientWave": "sentientwave.com",
  "Stealth Mode": "",
  /* Added 30 Sep 2026 from VentureOS portfolio records */
  "Valis": "valis.so",
  "CARYATID": "caryatid.ai",
  "blockrun": "blockrun.ai",
  "All3": "all3.com",
  "AeroSilicon": "aerosilicon.it",
  "Desk": "desk.us",
  "Vela": "getvela.com",
  "AIC": "aicomputefutures.com",
  "Autonomous Minds": "milo.ai",
  "Arete Studios": "aretestudios.com",
  "QTPIE": "sapios.io",
  "servamind": "servamind.com",
  "FAIRWAY": "fairwayrent.ai",
  "Positronic Robotics": "positronic.ro",
  "Stanislavsky AI": "stanislavsky.ai",
  "Savvy KID": "savvykid.app",
  "Boldr": "shopboldr.com",
  "getstaxel": "getstaxel.com",
  "Vernex": "vernex.com",
  "Explee": "explee.com",
  "dataprana": "dataprana.io",
  "Autonomics": "autonomics.tech",
  "NeeraLab": "neeralab.com",
  "pact": "withpact.com",
  "agnify": "agnify.ai",
  "Sava": "savahq.com",
  "Plan Monster": "planmonster.com",
  "novogaia": "novogaia.bio",
  "Grego": "grego.ai",
  "GenPeach AI": "genpeach.ai",
  "Slice & Dice": "slicedice.ai",
  "Mozart": "getmozart.ai",
  "Plurio": "ellyanalytics.com",
  "TaxRay": "taxray.ai",
  "Octrace": "octrace.ai",
  "API Nexus": "",
  "Embodix": "embodix.ai",
  "Subconscious": "subconscious.ai",
  "Monolith": "getmonolith.com",
  "Beagle": "discoverbeagle.com",
  "HelloCreator": "hellocreator.com",
  "Essence": "theessence.app",
  "Dicer.ai": "dicer.ai",
  "Endless Adventures": "adventureforge.games",
  "CreAitor": "",
  "NoCap": "nocap.so",
  "The Team": "theteam.ai",
  "SpellWise": "spellwise.ai",
  "Respell": "respell.ai",
  "Locals": "locals.org",
  "Performetry": "performetry.ai",
  "Mighty Health": "mightyhealth.com",
  "Birthday App": "birthday.app",
  "HealthRhythms": "healthrhythms.com",
  "Area of Games": "",
  "AiSupervision": "aisupervision.com",
  "Fogbender": "fogbender.com",
  "Classtag": "classtag.com",
  "RemBrain": "rembrain.ai",
  "Product Science": "productscience.ai",
  "WLNC": "welovenocode.com",
  "3D Predict": "3dpredict.com",
  "Machinet": "machinet.net",
  "LovOn": "lovon.app",
  "codemaestro": "code-maestro.com",
  "Thoughtful Lab": "corememily.com"
};
